name: books
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true
